default:
  asgi:
    host: 0.0.0.0
    port: 8000
    debug: false

  logging:
    level: INFO
    json_format: false

  db:
    debug: false

  cache:
    assignment_ttl: 5400
    client: redis

  auth:
    public_key_path: configs/jwt-pubkey.pem
    refresh_cookie_key: auth_refresh_token
    access_header_key: X-New-Access-Token
    issuer: auth-service
    audience: auth-client
    refresh_cookie_max_age: 12h

test:
  asgi:
    debug: true

  logging:
    level: DEBUG
    json_format: false

dev:
  logging:
    level: INFO
    json_format: true
